pipeline:
  stages:
    - name: Build and Test
      parallel:
        stages:
          - name: Go Build and Test
            steps:
              - name: Checkout Go Code
                run: git checkout main
              - name: Build Go Project
                run: go build
          - name: Node Build and Test Prod
            steps:
              - name: Checkout Node Code
                run: git checkout main
              - name: Install Node Dependencies
                run: npm install
    - name: Deploy
      steps:
        - name: Checkout Deployment Code
          run: git checkout main
        - name: Build Application for Deployment
          run: go build
        - name: Package Application
          run: tar -czf app.tar.gz ./app
        - name: Upload Package
          run: aws s3 cp app.tar.gz s3://my-bucket/app.tar.gz
