pipeline:
  name: test
  identifier: test
  projectIdentifier: anuragtest
  orgIdentifier: default
  tags: {}
  stages:
    - parallel:
        - stage:
            name: CI-1
            identifier: CI1
            description: ''
            type: CI
            spec:
              cloneCodebase: true
              caching:
                enabled: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Run_1
                      identifier: Run_1
                      spec:
                        shell: Sh
                        command: echo "hello1"
                  - step:
                      type: Run
                      name: Run_2
                      identifier: Run_2
                      spec:
                        shell: Sh
                        command: echo "hello2"
        - stage:
            name: CI-2
            identifier: CI2
            description: ''
            type: CI
            spec:
              cloneCodebase: true
              caching:
                enabled: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Run_3
                      identifier: Run_3
                      spec:
                        shell: Sh
                        command: echo "hello3"
                  - parallel:
                      - step:
                          type: Run
                          name: Run_4
                          identifier: Run_4
                          spec:
                            shell: Sh
                            command: echo 'serial'
                      - step:
                          type: Run
                          name: Run_5
                          identifier: Run_5
                          spec:
                            shell: Sh
                            command: echo "hello4"
    - stage:
        name: CI-3
        identifier: CI3
        description: ''
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_6
                  identifier: Run_6
                  spec:
                    shell: Sh
                    command: echo 'ci3'
              - step:
                  type: Run
                  name: Run_7
                  identifier: Run_7
                  spec:
                    shell: Sh
                    command: echo 'ci3-2'
  variables:
    - name: test
      type: String
      description: ''
      required: false
      value: test
    - name: test2
      type: String
      description: ''
      required: false
      value: test2
  timeout: 1h
