name: Build, Lint, Test
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Lint
        run: pnpm lint
  prettier:
    runs-on: ubuntu-22.04
    steps:
      - name: Prettier
        run: pnpm pretty
  typecheck:
    runs-on: ubuntu-22.04
    steps:
      - name: Typecheck
        run: pnpm typecheck
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: |
          pnpm install
          pnpm deps

      - name: Build all packages
        run: pnpm run build
