name: PR Checks
on:
  push:

jobs:
  Lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use pnpm
        uses: pnpm/action-setup@v4
      - name: Lint
        run: pnpm lint
  Prettier:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use pnpm
        uses: pnpm/action-setup@v4
      - name: Prettier
        run: pnpm pretty
  Typecheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use pnpm
        uses: pnpm/action-setup@v4
      - name: Typecheck
        run: pnpm typecheck
  Build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: |
          pnpm install
          pnpm deps

      - name: Build all packages
        run: pnpm run build
